INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = PinkyPonk

PinkyPonk_FILES = Tweak.xm
PinkyPonk_CFLAGS = -fobjc-arc
PinkyPonk_EXTRA_FRAMEWORKS += Cephei

include $(THEOS_MAKE_PATH)/tweak.mk